caseSensitive: false

labelMappings:
  feat: feat
  fix: fix
  docs: docs
  style: style
  refactor: refactor
  perf: perf
  test: test
  build: build
  ci: ci
  chore: chore
  revert: revert
  wip: wip
