changelog:
  categories:
    - title: feat
      labels:
        - feat
    - title: fix
      labels:
        - fix
    - title: docs
      labels:
        - docs
    - title: style
      labels:
        - style
    - title: refactor
      labels:
        - refactor
    - title: perf
      labels:
        - perf
    - title: test
      labels:
        - test
    - title: build
      labels:
        - build
    - title: ci
      labels:
        - ci
    - title: chore
      labels:
        - chore
    - title: ci
      labels:
        - ci
    - title: revert
      labels:
        - revert
